ARG 
FROM almalinux:${version:-8}
# ARG variable before FROM will not work after FROM

ARG course
ARG trainer
ENV course=${course:-Docker}
ENV trainer=${trainer:-JanardhanReddy}
RUN echo "Course Name is $course" , "Trainer  is $trainer"  